<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Close</name>
   <tag></tag>
   <elementGuidId>9c2f56dc-0d3d-4e37-89ef-f443542ebc17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dismiss-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dismiss-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close ad&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d441d31a-57cb-4d59-8085-c860ffc1d992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ns-9b2d8-e-16 button-common close-button milo-animation delay-4</value>
      <webElementGuid>b25b736b-14b6-4caa-ba71-fe707b6d924e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dismiss-button</value>
      <webElementGuid>6a60275e-f71a-4bf1-93f7-f69b1145d904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close ad</value>
      <webElementGuid>36b3401a-de9f-4ef9-af37-2481480c97c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>193a0efa-04fa-4559-b3d4-7aa03276f367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>16143f92-f91d-4441-afd2-74052fe557e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>3e37569f-7d0d-4fca-b8d6-1b0f71061c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dismiss-button&quot;)</value>
      <webElementGuid>d6c7f654-18db-4c79-b238-5367d76050e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FourthTest/Page_DEMOQA/iframe_Ad_ad_iframe</value>
      <webElementGuid>4e707d9b-0060-4ed3-a0c6-c0f4f0c2bc52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dismiss-button']</value>
      <webElementGuid>2b693d5c-58ae-4583-ad22-1490018f1bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='large-banner-eta-vanilla']/div/div[2]/div/div/div[3]</value>
      <webElementGuid>38d141de-b35e-4f07-b878-a867309b8bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='solinaut.ch'])[1]/following::div[2]</value>
      <webElementGuid>50a696db-14c6-483c-bdcb-8d7855f46b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solinaut GmbH - Ihr Partner für Automationslösungen'])[1]/following::div[7]</value>
      <webElementGuid>c3bfb582-a443-4039-9c3d-375c0c35d051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::div[3]</value>
      <webElementGuid>70f9dae6-cb01-43c3-b2bd-97570bc7559f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]</value>
      <webElementGuid>e1604f39-cf82-4f52-b18c-668a496be659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dismiss-button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>2b2c9196-8e33-496c-834b-4ba8ffffa99d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
