<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Only Y</name>
   <tag></tag>
   <elementGuidId>c3203534-8623-4f28-a599-b1b7b2e3cbf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='restrictedY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#restrictedY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Only Y&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3294af07-34b6-4285-b4ac-ed15f808e941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>restrictedY</value>
      <webElementGuid>a6483ee3-2ea8-4e0b-8c34-00608a7f6706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drag-box ui-draggable ui-draggable-handle</value>
      <webElementGuid>f906dcd1-ddaf-41e4-b844-ec4917037c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Only Y</value>
      <webElementGuid>23347e71-ebaf-4a46-b3b5-3aaff1d5974c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;restrictedY&quot;)</value>
      <webElementGuid>a3a97284-8726-40fe-b898-015d2f3bfdba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='restrictedY']</value>
      <webElementGuid>ee179b5c-2e9d-4895-834b-bb7b32a96ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='draggableExample-tabpane-axisRestriction']/div/div[2]</value>
      <webElementGuid>0e321288-a719-4a5a-a32b-a351e6c57d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only X'])[1]/following::div[1]</value>
      <webElementGuid>c9a1abf8-09a9-4b02-bd00-4b2bf5bc90d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag me'])[1]/following::div[4]</value>
      <webElementGuid>fb90709f-cf58-4552-a783-d18b94020d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Only Y']/parent::*</value>
      <webElementGuid>8be26d9e-d886-420a-b62d-fa223c8446db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>b3eeb0ea-51d6-449d-bd15-fc4ec65a6cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'restrictedY' and (text() = 'Only Y' or . = 'Only Y')]</value>
      <webElementGuid>a589b767-6a06-4e6a-b945-2fbbda18573d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
