<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Why do we use it</name>
   <tag></tag>
   <elementGuidId>85561cad-1b8c-4867-8ca5-94e91b09dd50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#section3Heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section3Heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Why do we use it?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d40417f-5009-45f3-ba09-1c950d01e0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>b4935efc-474f-4631-bd2b-b6518746964e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>section3Heading</value>
      <webElementGuid>ee2917d7-3598-4eb6-9a97-0dfd52abc730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Why do we use it?</value>
      <webElementGuid>59c1029d-5713-47c2-a2b0-ae6bba29127f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section3Heading&quot;)</value>
      <webElementGuid>9a33a35f-0154-4a6c-b9ae-1680d17244af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='section3Heading']</value>
      <webElementGuid>7bc38f94-656d-4a36-a95d-a25a01faf388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordianContainer']/div/div[3]/div</value>
      <webElementGuid>11258a83-908c-414f-be24-a22f257079c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where does it come from?'])[1]/following::div[4]</value>
      <webElementGuid>a17cb39b-9c7d-4d88-a7f1-c445ab68b139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is Lorem Ipsum?'])[1]/following::div[8]</value>
      <webElementGuid>0340c5ca-d5a2-4395-b812-21cf6300dd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::div[15]</value>
      <webElementGuid>a87b7da7-259d-4eee-879d-46254a7265c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Why do we use it?']/parent::*</value>
      <webElementGuid>91aaa4b5-7498-46d1-a6e4-235ee9aaea13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div</value>
      <webElementGuid>1dd6f42c-2594-4acf-8856-15baa7634e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'section3Heading' and (text() = 'Why do we use it?' or . = 'Why do we use it?')]</value>
      <webElementGuid>ae4895f5-86e7-44aa-91a8-bba079fdab70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
