<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Where does it come from</name>
   <tag></tag>
   <elementGuidId>9053fa19-b6f3-4f7d-b393-11aa0745940d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#section2Heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section2Heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Where does it come from?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3746773-d2ac-47de-8bb5-08346a1ce034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>a6cc4fbc-4cf0-460c-bd2a-950134d71c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>section2Heading</value>
      <webElementGuid>d6d42d98-e303-4643-91de-e5825a839b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Where does it come from?</value>
      <webElementGuid>3c139bb4-2578-4138-baac-73fbaae3e730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section2Heading&quot;)</value>
      <webElementGuid>54d28a9a-831f-46f8-b223-085db87b32bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='section2Heading']</value>
      <webElementGuid>ee636bbf-8945-4403-8842-2a685d5e4bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordianContainer']/div/div[2]/div</value>
      <webElementGuid>5a72f0b1-eac4-45d2-9e35-137c89daf566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is Lorem Ipsum?'])[1]/following::div[4]</value>
      <webElementGuid>00ab7d48-7061-4037-92f5-90bf3294ec44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accordian'])[2]/following::div[7]</value>
      <webElementGuid>0e8e3969-26ad-4f0e-94c4-3f2cc5f188b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why do we use it?'])[1]/preceding::div[3]</value>
      <webElementGuid>9f4ccd43-3745-4e80-bad7-9d2568c8a425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::div[19]</value>
      <webElementGuid>03579ed8-d172-4a1f-9f0e-65d946129f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Where does it come from?']/parent::*</value>
      <webElementGuid>73b1531e-efe4-4222-b8f2-c7363691eb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>5a25fc53-be99-4889-8e91-07882cc1e7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'section2Heading' and (text() = 'Where does it come from?' or . = 'Where does it come from?')]</value>
      <webElementGuid>6cc49ed5-6b86-4010-b71d-36803bd16956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
