<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Date_datePickerMonthYearInput</name>
   <tag></tag>
   <elementGuidId>62ede451-b201-4207-b5e3-fb233a5359f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datePickerMonthYearInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datePickerMonthYearInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#datePickerMonthYearInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f454bd4-3919-4c28-be09-6d929158bf3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c93f47a-ac1c-474f-8456-8800c3c342ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datePickerMonthYearInput</value>
      <webElementGuid>54aeddd1-4744-470d-86e0-70256d6d7b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>71eadea0-ebaa-4a7d-b24b-f409a3da0bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>07/22/2025</value>
      <webElementGuid>773fbc81-7b2e-4e13-b9a9-3660a372ce8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datePickerMonthYearInput&quot;)</value>
      <webElementGuid>3c55e707-79d5-4e7b-8e1a-ea31b90ae948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datePickerMonthYearInput']</value>
      <webElementGuid>e7161e55-2d4b-4f29-bedb-0e4cd6970c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datePickerMonthYear']/div/div/input</value>
      <webElementGuid>e3165ee6-e5ba-4922-a59d-c41430ee972d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c212708f-353e-49f3-a285-10b74e17f848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datePickerMonthYearInput']</value>
      <webElementGuid>b24f3155-55f8-4fbc-ad29-0ec391ee7e28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
