<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_WhatOriginUseMore</name>
   <tag></tag>
   <elementGuidId>72e953f4-aeac-4d5a-bba5-2192f928e712</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.nav.nav-tabs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabsContainer']/nav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;WhatOriginUseMore&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>54a0e170-ba29-4e0f-9d63-0abaa78f25b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav nav-tabs</value>
      <webElementGuid>e3c09e96-c47c-4b6f-80dd-223f9678a661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tablist</value>
      <webElementGuid>f7883290-f0de-45e9-9d8a-e326984f65f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WhatOriginUseMore</value>
      <webElementGuid>01021373-e462-4dc9-9ff4-d70fcb2101ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabsContainer&quot;)/nav[@class=&quot;nav nav-tabs&quot;]</value>
      <webElementGuid>d0c00247-7dce-49b2-b2ce-ca1c9768b938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabsContainer']/nav</value>
      <webElementGuid>6eacdd87-7155-45e3-8a88-bb4aad4c1721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details about Lorem Ipsum'])[1]/following::nav[1]</value>
      <webElementGuid>8ee179fc-b3a1-4c51-915c-deae3aa02ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tabs'])[2]/following::nav[1]</value>
      <webElementGuid>9fa9a77b-2085-4a3f-9224-7ef3031f60b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::nav[1]</value>
      <webElementGuid>524e64cb-ac36-44af-97c1-c1a6fc76d08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav</value>
      <webElementGuid>cbefe588-6da3-48a9-9e33-a6ed1559fafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'WhatOriginUseMore' or . = 'WhatOriginUseMore')]</value>
      <webElementGuid>6094c8cd-801e-4cb5-938a-9be6e07c6bf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
