<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Department_department</name>
   <tag></tag>
   <elementGuidId>3a15c666-e6f0-4d2c-b1d6-20520822f9ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#department</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='department']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Department&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b753968b-3217-4d9c-a9ea-dbc35307b39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>f2a4381d-4e2e-46b8-8b8b-3f9c727ec978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>80583852-cd4c-48f3-bce2-4a4311b345e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Department</value>
      <webElementGuid>30aa2341-e253-4fb0-a7a9-2d59028406ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f887626-1a58-48ec-9bc2-4be4e5b13a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>department</value>
      <webElementGuid>209d19cd-8a5d-450c-9b82-bfc73911a689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> mr-sm-2 form-control</value>
      <webElementGuid>92b2ed4a-d6bc-41c3-b498-41be9f84b393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department&quot;)</value>
      <webElementGuid>493c9d3d-6706-4990-9d60-38ea3e4700df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='department']</value>
      <webElementGuid>7e60e837-ed4d-495c-b58f-09bca1e72419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='department-wrapper']/div[2]/input</value>
      <webElementGuid>3548e3f3-09c9-406b-a2ec-eac0d1eb0f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>af688ef6-0b99-490b-9724-8bfe91ef15ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Department' and @type = 'text' and @id = 'department']</value>
      <webElementGuid>4d4d4f06-68a9-4f3b-8493-b4c802badd9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
